---
title: "Question2"
author: "Bejan Sadeghian"
date: "August 7, 2015"
output: html_document
---

###Question 2 of Homework 1

####Objective
We were given a account with $100,000 in it and asked to create three different scenarios where we invest the money into a portfolio of five ETFs that each applied one of the descriptions below

 - No. 1 even split between the five,
 - No. 2 a safer portfolio
 - No. 3 a more aggressive portfolio
 
ETF's we will be using are {SPY, TLT, LQD, EEM, VNQ}

####Conclusion
I am happy to see that my safe portfolio had the least 5% VaR of the three. 
My reasons for choosing the weights of the ETFs in my safe portfolio are below...
 
 - For a safer portfolio, Id wanted to invest in ETFs that appear to be uncorrelated or inversely correlated to one another. This was to avoid multiplicative losses (one goes down, both go down). Also I want to choose a stock that does not have a high STD of percent change from day to day.
My reasons for choosing the weights of the ETFs in my aggressive portfolio are similar to my reasons for the safe portfolio but comments I included in my code are below...
 
 - For higher risk ETFs Id say investing more of my portfolio on ETFs that seem correlated to one another will result in higher risk because when one goes up both do and my returns are increased by that combination. But, like any risky portfolio, if one ETF goes down, the other tends to go down as well. 

To accomplish the assessment of correlation and risk of each ETF and their combinations I created the pairs plot mentioned below and calculated STD for each ETF over the last year. I used correlation and STD to determine if a ETF combination was safe (no correlation and low STD) or risky (high correlation and high STD)

You can see 

####Method for Solution
Step 1) Import the fImport and foreach libraries to allow pulling from Yahoo and using the foreach function
```
library(fImport)
library(foreach)
library(mosaic)

set.seed(1)
```

Step 2) Create the function YahooPricesToReturns and import yahoo data as a series for the five ETFs.

```
Stockdata = yahooSeries(c('SPY','TLT','LQD','EEM','VNQ'), to=Sys.timeDate(), nDaysBack = 1825)

YahooPricesToReturns = function(series) { #YahooPricesToReturns Function Code provided by Dr. James Scott
  mycols = grep('Adj.Close', colnames(series))
  closingprice = series[,mycols]
  N = nrow(closingprice)
  percentreturn = as.data.frame(closingprice[2:N,]) / as.data.frame(closingprice[1:(N-1),]) - 1
  mynames = strsplit(colnames(percentreturn), '.', fixed=TRUE)
  mynames = lapply(mynames, function(x) return(paste0(x[1], ".PctReturn")))
  colnames(percentreturn) = mynames
  as.matrix(na.omit(percentreturn))
}
```

Step 3) To be able to determine what my safe and aggressive portfolio will consist of, I create a pairs plot to see what correlations exist between the five ETFs. I then select my weights for the safe and aggressive portfolios as mentioned in the comment blocks included in the code just below.
```
#Assessing risk of each ETF
myreturns = YahooPricesToReturns(Stockdata)
pairs(myreturns)
print('Column STD')
apply(myreturns,2,sd)


#Assigning weights to each portfolio 
WeightsEven = c(0.2, 0.2, 0.2, 0.2, 0.2) #SPY, TLT, LQD, EEM, VNQ

#for a safer portfolio, Id like to invest in stocks that appear to be uncorrelated or 
#inversely correlated  to one another, to avoid multiplicative losses. Also I want to 
#choose a stock that does not have a high STD of percent change from day to day
WeightsSafe = c(0.33, 0.34, 0.33, 0.0, 0.0) #SPY, TLT, LQD, EEM, VNQ

#for higher risk ETFs Id say investing more of my portfolio on ETFs that seem
#correlated to one another will result in higher risk because when one goes up both
#do, but if one goes down, the other tends to go down as well. 
WeightsAggr = c(0.3, 0.0, 0.0, 0.35, 0.35) #SPY, TLT, LQD, EEM, VNQ

IniWealth = 100000 #invest $100,000 initially
```

Step 4) I then initialize the wealth at $100,000 and begin bootstrapping the Yahoo dataset for each stock 20 times. I then repeat the bootstrapping 5000 times to give myself a dataset to use for the final piece of this project that I will explain later. (These 5000 wealth instances are saved as EvenSim, SafeSim, & AggSim)
```
IniWealth = 100000 #invest $100,000 initially


#Begin bootstrap for each portfolio
#Even Split Portfolio
EvenSim = foreach(i=1:5000, .combine='rbind') %do% {
  totwealth = IniWealth
  ndays=20
  wealthTracker = rep(0,ndays)
  for(i in 1:ndays){
    currentWealth = totwealth * WeightsEven
    dailyChange = resample(myreturns,1, orig.id=FALSE) #bootstrap sample for the day
    newHoldings = currentWealth + currentWealth*dailyChange
    totwealth = sum(newHoldings)
    wealthTracker[i] = totwealth
  }
  wealthTracker
}
plot(wealthTracker, type='l', main='Even Split Portfolio', xlab='Trading Days', ylab='Wealth')

#Safe Portfolio
SafeSim = foreach(i=1:5000, .combine='rbind') %do% {
  totwealth = IniWealth
  ndays=20
  wealthTracker = rep(0,ndays)
  for(i in 1:ndays){
    currentWealth = totwealth * WeightsSafe
    dailyChange = resample(myreturns,1, orig.id=FALSE) #bootstrap sample for the day
    newHoldings = currentWealth + currentWealth*dailyChange
    totwealth = sum(newHoldings)
    wealthTracker[i] = totwealth
  }
wealthTracker
}
plot(wealthTracker, type='l', main='Safe Portfolio', xlab='Trading Days', ylab='Wealth')


#Aggressive Portfolio
AggSim = foreach(i=1:5000, .combine='rbind') %do% {
  totwealth = IniWealth
  ndays=20
  wealthTracker = rep(0,ndays)
  for(i in 1:ndays){
    currentWealth = totwealth * WeightsAggr
    dailyChange = resample(myreturns,1, orig.id=FALSE) #bootstrap sample for the day
    newHoldings = currentWealth + currentWealth*dailyChange
    totwealth = sum(newHoldings)
    wealthTracker[i] = totwealth
  }
  wealthTracker
}
plot(wealthTracker, type='l', main='Aggressive Portfolio', xlab='Trading Days', ylab='Wealth')

```

Step 5) Finally, I calculate the 5% Value at Risk for each portfolio. 

 - 5% Value at Risk (VaR) is the amount of money to where I have a 5% probability of losing that amount or more after 20 trading days using the given portfolio.
 
```
#Now calculate the 5% value at risk for each of these three portfolios
print('Even Split')
quantile(EvenSim[,n_days], 0.05) - 100000

print('Safe Portfolio')
quantile(SafeSim[,n_days], 0.05) - 100000

print('Aggressive Portfolio')
quantile(AggSim[,n_days], 0.05) - 100000
```

```{R, fig.width=5, fig.height = 4, message=FALSE}
library(fImport)
library(foreach)
library(mosaic)

set.seed(1)
#Import the last five years worth of data
Stockdata = yahooSeries(c('SPY','TLT','LQD','EEM','VNQ'), to=Sys.timeDate(), nDaysBack = 1825)

YahooPricesToReturns = function(series) { #YahooPricesToReturns Function Code provided by Dr. James Scott
  mycols = grep('Adj.Close', colnames(series))
  closingprice = series[,mycols]
  N = nrow(closingprice)
  percentreturn = as.data.frame(closingprice[2:N,]) / as.data.frame(closingprice[1:(N-1),]) - 1
  mynames = strsplit(colnames(percentreturn), '.', fixed=TRUE)
  mynames = lapply(mynames, function(x) return(paste0(x[1], ".PctReturn")))
  colnames(percentreturn) = mynames
  as.matrix(na.omit(percentreturn))
}

#Assessing risk of each ETF
myreturns = YahooPricesToReturns(Stockdata)
pairs(myreturns)
print('Column STD')
apply(myreturns,2,sd)


#Assigning weights to each portfolio 
WeightsEven = c(0.2, 0.2, 0.2, 0.2, 0.2) #SPY, TLT, LQD, EEM, VNQ

#for a safer portfolio, Id like to invest in stocks that appear to be uncorrelated or 
#unversely correlated  to one another, to avoid multiplicative losses. Also I want to 
#choose a stock that does not have a high STD of percent change from day to day
WeightsSafe = c(0.33, 0.34, 0.33, 0.0, 0.0) #SPY, TLT, LQD, EEM, VNQ

#for higher risk ETFs Id say investing more of my portfolio on ETFs that seem
#correlated to one another will result in higher risk because when one goes up both
#do, but if one goes down, the other tends to go down as well. 
WeightsAggr = c(0.3, 0.0, 0.0, 0.35, 0.35) #SPY, TLT, LQD, EEM, VNQ

IniWealth = 100000 #invest $100,000 initially
ndays=20

#Begin bootstrap for each portfolio
#Even Split Portfolio
EvenSim = foreach(i=1:5000, .combine='rbind') %do% {
  totwealth = IniWealth
  wealthTracker = rep(0,ndays)
  for(i in 1:ndays){
    currentWealth = totwealth * WeightsEven
    dailyChange = resample(myreturns,1, orig.id=FALSE) #bootstrap sample for the day
    newHoldings = currentWealth + currentWealth*dailyChange
    totwealth = sum(newHoldings)
    wealthTracker[i] = totwealth
  }
  wealthTracker
}
plot(wealthTracker, type='l', main='Even Split Portfolio', xlab='Trading Days', ylab='Wealth')

#Safe Portfolio
SafeSim = foreach(i=1:5000, .combine='rbind') %do% {
  totwealth = IniWealth
  wealthTracker = rep(0,ndays)
  for(i in 1:ndays){
    currentWealth = totwealth * WeightsSafe
    dailyChange = resample(myreturns,1, orig.id=FALSE) #bootstrap sample for the day
    newHoldings = currentWealth + currentWealth*dailyChange
    totwealth = sum(newHoldings)
    wealthTracker[i] = totwealth
  }
wealthTracker
}
plot(wealthTracker, type='l', main='Safe Portfolio', xlab='Trading Days', ylab='Wealth')


#Aggressive Portfolio
AggSim = foreach(i=1:5000, .combine='rbind') %do% {
  totwealth = IniWealth
  wealthTracker = rep(0,ndays)
  for(i in 1:ndays){
    currentWealth = totwealth * WeightsAggr
    dailyChange = resample(myreturns,1, orig.id=FALSE) #bootstrap sample for the day
    newHoldings = currentWealth + currentWealth*dailyChange
    totwealth = sum(newHoldings)
    wealthTracker[i] = totwealth
  }
  wealthTracker
}
plot(wealthTracker, type='l', main='Aggressive Portfolio', xlab='Trading Days', ylab='Wealth')


#Now calculate the 5% value at risk for each of these three portfolios
print('Even Split')
quantile(EvenSim[,ndays], 0.05) - 100000

print('Safe Portfolio')
quantile(SafeSim[,ndays], 0.05) - 100000

print('Aggressive Portfolio')
quantile(AggSim[,ndays], 0.05) - 100000
```